### ISSUE TITLE
TypeError in groupby mean aggregation

### ISSUE THREAD

**Issue by hamzaibrahim21** [Bayer-Group/mlr-xai-selfies#1]
Thank you for providing this useful tool. However, I've encountered a bug during code execution.

## Description
When attempting to perform a mean aggregation using `groupby().mean()` on a DataFrame, a `TypeError` occurs. The dataframe appears to contain mixed data types, including strings and numerical values which can be found in this [line.](https://github.com/Bayer-Group/mlr-xai-selfies/blob/b0620c801f4352bd9561df1670ed2dacf4e7d99d/xai_selfies/main.py#L250C5-L250C5)

To reproduce, execute `examply.py` and it leads to `TypeError: Could not convert string 'Cn1c(CN2CCN(CC2)c3ccc(Cl)cc3)...' to numeric`

## Suggestion
Grouping by `mutation_pos` only and then using `select_dtypes(include=[int, float])` to filter only integer or float columns worked perfectly for me.

**Comment by jmwoll** [comment]
Looking into it right now. Sorry for the late reply.

~~Just to make sure I understand it correctly: did you encounter this issue with the `example.py` script on the suggested `Lipophilicity.csv` dataset?~~
Had the same issue with the `example.py `script on `Lipophilicity.csv`

**Comment by jmwoll** [comment]
The mean aggregation should indeed be performed only on the column of interest, instead of the whole dataframe, which might lead to issues depending on your input datasets.
I have to take care of some administrative things right now to get maintainer access. Your fix with select_dtypes should fix the issues that you encountered, and also lead to semantically correct results.
 
The way I see it:
In the line pointed out by you a mean aggregation is performed on the dataframe, while it should only be performed on the column of interest (`'difference'`). 
I think the simplest solution will be to perform the mean aggregation only on this "difference" column. 

In any case, thanks for bringing this issue to our attention.
@hamzaibrahim21 If you want you can make a PR with your changes and I would review it as soon as I got the maintainer rights. Otherwise I would also push a fix soon.

**Comment by jmwoll** [comment]
The issue should be resolved now, otherwise let me know and I reopen the issue.
